<?php
return 'DROP TABLE IF EXISTS `[ENTITY_NAME]`;
CREATE TABLE `[ENTITY_NAME]`
(
    `id` int(11) NOT NULL AUTO_INCREMENT,
[PROPERTIES]
    PRIMARY KEY (`id`)
)AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;';